name: Update repo

on:
  push:
    tags:
      - v*

jobs:
  default:
    if: github.repository == 'zim514/script.module.qhue'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.9 ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repository: 'zim514/zim514.github.io'
          token: ${{ github.token }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install gitpython

      - name: Generate repo
        run: |
          git rm -rf *.md5 *.zip
          ./create_repository.py --datadir=docs/repo https://github.com/zim514/script.service.hue.git:script.service.hue https://github.com/zim514/script.module.qhue:script.module.qhue https://github.com/zim514/zim514.github.io.git:repository.snapcase
        working-directory: ./

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated repo update ${{ github.ref }}
          add_options: '--all'
